### PR TITLE
add french translation

### PR DESCRIPTION
**Pull request by NicolasKAROLAK**

### CODE REVIEW

**Comment by DH3ALEJANDRO** [comment]
I'm having problems with registration.
I think this site has fallen https://brackets-registry.aboutweb.com?

**Comment by NicolasKAROLAK** [comment]
Same for me. And for isup.me ass well : http://www.isup.me/brackets-registry.aboutweb.com

**Comment by DH3ALEJANDRO** [comment]
There! :) please update.

**Comment by NicolasKAROLAK** [comment]
Updated, thanks.

**Pull request closed without merging**
